version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: nestJs
    ports:
      - "3000:3000"
    restart: "always"
    env_file:
      - ./env/.env
    volumes:
      - ../backend-auguest-thirty-first:/home
    networks:
      - gaepo

networks:
    gaepo:
        driver: bridge