version: '3.8'

services:
  backend:
    container_name: nestJs
    image: nestjs:alpine
    build:
      context: ./nestjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: "always"
    env_file:
      - ../env/.env
    volumes:
      - ../:/home
    networks:
      - gaepo

  postgres:
    container_name: postgres
    image: postgresql:alpine
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ../env/.env

networks:
    gaepo:
        driver: bridge

  
