#/bin/sh

#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "$PONG_USER" PASSWORD '$PONG_PASSWORD';
	CREATE DATABASE "$PONG_DATABASE" OWNER "$PONG_USER";
	GRANT ALL PRIVILEGES ON DATABASE "$PONG_DATABASE" TO "$PONG_USER";
EOSQL
