name: compile
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          submodules: true
      - name: check compile
        working-directory: ./nestjs
        run: 
          npx tsc && npm run lint
