name: Tests
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          submodules: true
      - name: run test
        run: make test
