name: Tests
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          submodules: true
      - name: run ls
        run: ls -al env
      - name: change src dir
        run: cd nestjs
      - name: Install modules
        run: npm install
      - name: Install modules ci
        run: npm ci
      - name: Run tests
        run: npm run test
